-- Development-only runtime controls. These definitions are the single source
-- of truth for the admin tuning panel and for headless validation.
--
-- IDs are deliberately stable and namespaced. Gameplay systems read values
-- through the Tuning service; they never inspect UI labels or duplicate ranges.

return {
  {
    id = "simulation.time_scale",
    category = "Simulation",
    label = "Game speed",
    help = "Scales simulation time without changing menu input.",
    value_type = "number",
    default = 1.0,
    min = 0.1,
    max = 3.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "test.enhanced_mode",
    category = "Simulation",
    label = "5x test mode",
    help = "Boosts speed, power, XP gain and XP-gem magnetism by five.",
    value_type = "boolean",
    default = false,
  },
  {
    id = "player.speed_multiplier",
    category = "Player",
    label = "Player speed",
    help = "Multiplies Joe's movement speed.",
    value_type = "number",
    default = 1.0,
    min = 0.25,
    max = 3.0,
    step = 0.05,
    decimals = 2,
  },
  {
    id = "player.invincible",
    category = "Player",
    label = "Invincible",
    help = "Prevents player damage in development builds.",
    value_type = "boolean",
    default = false,
  },
  {
    id = "combat.fire_rate_multiplier",
    category = "Combat",
    label = "Fire-rate multiplier",
    help = "Higher values reduce the time between weapon activations.",
    value_type = "number",
    default = 1.0,
    min = 0.1,
    max = 8.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "combat.damage_multiplier",
    category = "Combat",
    label = "Damage multiplier",
    help = "Multiplies damage when a projectile is created.",
    value_type = "number",
    default = 1.0,
    min = 0.1,
    max = 10.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "combat.knockback_multiplier",
    category = "Combat",
    label = "Hit knockback",
    help = "Scales projectile push and player recoil from enemy attacks.",
    value_type = "number",
    default = 1.0,
    min = 0.0,
    max = 4.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "projectiles.speed_multiplier",
    category = "Projectiles",
    label = "Bullet speed",
    help = "Multiplies projectile travel speed.",
    value_type = "number",
    default = 1.0,
    min = 0.25,
    max = 5.0,
    step = 0.05,
    decimals = 2,
  },
  {
    id = "projectiles.per_shot_bonus",
    category = "Projectiles",
    label = "Extra bullets per shot",
    help = "Adds projectiles to every weapon activation.",
    value_type = "integer",
    default = 0,
    min = 0,
    max = 12,
    step = 1,
  },
  {
    id = "projectiles.max_active",
    category = "Projectiles",
    label = "Maximum active bullets",
    help = "Hard safety cap for live projectiles.",
    value_type = "integer",
    default = 500,
    min = 25,
    max = 3000,
    step = 25,
  },
  {
    id = "enemies.speed_multiplier",
    category = "Enemies",
    label = "Enemy speed",
    help = "Multiplies enemy movement speed.",
    value_type = "number",
    default = 1.0,
    min = 0.1,
    max = 4.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "enemies.spawn_rate_multiplier",
    category = "Enemies",
    label = "Spawn-rate multiplier",
    help = "Higher values shorten the time between spawns.",
    value_type = "number",
    default = 1.0,
    min = 0.1,
    max = 10.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "enemies.damage_multiplier",
    category = "Enemies",
    label = "Enemy damage",
    help = "Scales enemy contact, pulse and note-projectile damage.",
    value_type = "number",
    default = 1.0,
    min = 0.1,
    max = 5.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "enemies.max_active",
    category = "Enemies",
    label = "Maximum active enemies",
    help = "Hard safety cap for live enemies.",
    value_type = "integer",
    default = 350,
    min = 10,
    max = 1500,
    step = 10,
  },
  {
    id = "rewards.xp_multiplier",
    category = "Rewards",
    label = "XP multiplier",
    help = "Multiplies XP at the single award point.",
    value_type = "number",
    default = 1.0,
    min = 0.1,
    max = 10.0,
    step = 0.1,
    decimals = 1,
  },
  {
    id = "pickups.radius_multiplier",
    category = "Rewards",
    label = "Pickup radius",
    help = "Multiplies the pickup attraction radius.",
    value_type = "number",
    default = 1.0,
    min = 0.25,
    max = 8.0,
    step = 0.25,
    decimals = 2,
  },
  {
    id = "ui.show_evolution_requirements",
    category = "Rewards",
    label = "Show evolution needs",
    help = "Shows paired support and missing rank requirements on level-up choices.",
    value_type = "boolean",
    default = true,
  },
  {
    id = "rewards.admin_rank1_evolution",
    category = "Rewards",
    label = "Allow rank-1 evolution",
    help = "Admin-only test bypass. Normal level-up fusion still requires rank 10.",
    value_type = "boolean",
    default = false,
  },
  {
    id = "beat.bpm_override",
    category = "Groove",
    label = "BPM override",
    help = "Zero uses track metadata; otherwise forces a development BPM.",
    value_type = "integer",
    default = 0,
    min = 0,
    max = 240,
    step = 1,
  },
  {
    id = "run.stage1_duration",
    category = "Run",
    label = "Stage 1 duration",
    help = "Playable Stage 1 length in seconds; defaults to three minutes.",
    value_type = "integer",
    default = 180,
    min = 60,
    max = 1200,
    step = 30,
  },
  {
    id = "run.stage2_duration",
    category = "Run",
    label = "Stage 2 duration",
    help = "Playable Orbit Line length in seconds; defaults to three minutes.",
    value_type = "integer",
    default = 180,
    min = 60,
    max = 1200,
    step = 30,
  },
  {
    id = "run.difficulty_ramp",
    category = "Run",
    label = "Difficulty escalation",
    help = "Scales the within-stage health, speed, damage and density ramp.",
    value_type = "number",
    default = 1.0,
    min = 0.25,
    max = 3.0,
    step = 0.05,
    decimals = 2,
  },
}
