-- Enemy definitions. All rhythmless creatures, no real-world references.

return {
  monotone = {
    id     = "monotone",
    name   = "Monotone",
    hp     = 20,
    speed  = 60,
    size   = 12,
    damage = 10,
    xp     = 10,
    coins  = 1,
    brain  = "chase",
    color  = { 0.85, 0.25, 0.25, 1 },
    sprite = { col = 1, row = 1 },
    sprite_size = 70,
  },

  tempo_leech = {
    id     = "tempo_leech",
    name   = "Tempo Leech",
    hp     = 45,
    speed  = 95,
    size   = 18,
    damage = 15,
    xp     = 20,
    coins  = 2,
    brain  = "zigzag",
    color  = { 0.95, 0.55, 0.2, 1 },
    sprite = { col = 2, row = 1 },
    sprite_size = 76,
  },

  metronome_guardian = {
    id = "metronome_guardian",
    name = "Metronome Guardian",
    hp = 900,
    speed = 72,
    size = 30,
    damage = 22,
    xp = 140,
    coins = 75,
    brain = "charger",
    boss_type = "miniboss",
    color = { 0.72, 0.35, 1.0, 1 },
    sprite = { col = 3, row = 1 },
    sprite_size = 108,
  },

  static_baron = {
    id = "static_baron",
    name = "Static Baron",
    hp = 3200,
    speed = 0,
    size = 46,
    damage = 18,
    xp = 500,
    coins = 250,
    brain = "static",
    boss_type = "final",
    attack_interval = 1.4,
    attack_range = 520,
    color = { 1.0, 0.18, 0.62, 1 },
    sprite = { col = 4, row = 1 },
    sprite_size = 132,
  },

  syncopation_skitter = {
    id = "syncopation_skitter",
    name = "Syncopation Skitter",
    hp = 34,
    speed = 138,
    size = 14,
    damage = 12,
    xp = 15,
    coins = 2,
    brain = "zigzag",
    color = { 0.25, 0.95, 1.0, 1 },
    sprite = { col = 1, row = 2 },
    sprite_size = 72,
  },

  feedback_phantom = {
    id = "feedback_phantom",
    name = "Feedback Phantom",
    hp = 80,
    speed = 76,
    size = 20,
    damage = 18,
    xp = 30,
    coins = 4,
    brain = "chase",
    color = { 0.36, 1.0, 0.54, 1 },
    sprite = { col = 2, row = 2 },
    sprite_size = 88,
  },

  bass_brute = {
    id = "bass_brute",
    name = "Bass Brute",
    hp = 180,
    speed = 52,
    size = 27,
    damage = 28,
    xp = 48,
    coins = 7,
    brain = "charger",
    color = { 1.0, 0.72, 0.20, 1 },
    sprite = { col = 3, row = 2 },
    sprite_size = 104,
  },

  noise_turret = {
    id = "noise_turret",
    name = "Noise Turret",
    hp = 115,
    speed = 0,
    size = 22,
    damage = 11,
    xp = 38,
    coins = 5,
    brain = "static",
    attack_interval = 2.1,
    attack_range = 420,
    color = { 0.28, 0.60, 1.0, 1 },
    sprite = { col = 4, row = 2 },
    sprite_size = 92,
  },

  vinyl_drone = {
    id = "vinyl_drone",
    name = "Vinyl Drone",
    hp = 95,
    speed = 92,
    size = 18,
    damage = 15,
    xp = 24,
    coins = 3,
    brain = "chase",
    color = { 0.72, 0.48, 1.0, 1 },
    sprite = { atlas = "stage2", col = 1, row = 1 },
    sprite_size = 78,
  },

  trumpet_ray = {
    id = "trumpet_ray",
    name = "Trumpet Ray",
    hp = 130,
    speed = 76,
    size = 19,
    damage = 16,
    xp = 34,
    coins = 4,
    brain = "ranged",
    attack_kind = "note_bolt",
    attack_interval = 2.1,
    attack_range = 520,
    preferred_range = 330,
    windup = 0.48,
    projectile_speed = 285,
    color = { 1.0, 0.66, 0.18, 1 },
    sprite = { atlas = "stage2", col = 2, row = 1 },
    sprite_size = 82,
  },

  drum_wheel = {
    id = "drum_wheel",
    name = "Drum Wheel",
    hp = 220,
    speed = 88,
    size = 24,
    damage = 24,
    xp = 44,
    coins = 6,
    brain = "charger",
    color = { 0.92, 0.34, 0.88, 1 },
    sprite = { atlas = "stage2", col = 3, row = 1 },
    sprite_size = 96,
  },

  theremin_jelly = {
    id = "theremin_jelly",
    name = "Theremin Jelly",
    hp = 175,
    speed = 58,
    size = 23,
    damage = 19,
    xp = 42,
    coins = 6,
    brain = "pulse",
    attack_kind = "resonance_pulse",
    attack_interval = 2.8,
    attack_range = 170,
    windup = 0.72,
    color = { 0.38, 0.90, 1.0, 1 },
    sprite = { atlas = "stage2", col = 4, row = 1 },
    sprite_size = 92,
  },

  amp_hound = {
    id = "amp_hound",
    name = "Amp Hound",
    hp = 420,
    speed = 132,
    size = 27,
    damage = 27,
    xp = 68,
    coins = 10,
    brain = "orbit",
    elite = true,
    color = { 0.48, 0.74, 1.0, 1 },
    sprite = { atlas = "stage2", col = 1, row = 2 },
    sprite_size = 108,
  },

  keyboard_centipede = {
    id = "keyboard_centipede",
    name = "Keyboard Centipede",
    hp = 560,
    speed = 82,
    size = 30,
    damage = 31,
    xp = 82,
    coins = 12,
    brain = "zigzag",
    elite = true,
    color = { 0.62, 0.34, 1.0, 1 },
    sprite = { atlas = "stage2", col = 2, row = 2 },
    sprite_size = 118,
  },

  turntable_sentinel = {
    id = "turntable_sentinel",
    name = "Turntable Sentinel",
    hp = 5200,
    speed = 44,
    size = 46,
    damage = 30,
    xp = 360,
    coins = 150,
    brain = "ranged",
    boss_type = "miniboss",
    attack_kind = "note_bolt",
    attack_interval = 1.25,
    attack_range = 680,
    preferred_range = 390,
    windup = 0.38,
    projectile_speed = 350,
    color = { 0.92, 0.42, 1.0, 1 },
    sprite = { atlas = "stage2", col = 3, row = 2 },
    sprite_size = 160,
  },

  grand_orchestrator = {
    id = "grand_orchestrator",
    name = "Grand Orchestrator",
    hp = 14500,
    speed = 34,
    size = 58,
    damage = 36,
    xp = 1000,
    coins = 500,
    brain = "pulse",
    boss_type = "final",
    attack_kind = "resonance_pulse",
    attack_interval = 1.75,
    attack_range = 250,
    windup = 0.62,
    color = { 1.0, 0.30, 0.74, 1 },
    sprite = { atlas = "stage2", col = 4, row = 2 },
    sprite_size = 205,
  },
}
