local function loop(id, path, bpm, gain, transition, beats)
  return {
    id = id,
    path = "assets/music/" .. path,
    bpm = bpm,
    beats = beats or 32,
    meter = 4,
    loop = true,
    gain = gain or 1,
    transition = transition or "crossfade",
  }
end

return {
  title = loop("title", "01_title.ogg", 112, 1.00),
  prologue_city = loop("prologue_city", "02_prologue_city.ogg", 92, 0.62),
  prologue_break = loop("prologue_break", "03_prologue_break.ogg", 100, 0.60),
  prologue_resolve = loop("prologue_resolve", "04_prologue_resolve.ogg", 116, 0.62),
  character_select = loop("character_select", "05_character_select.ogg", 120, 0.86),
  joe_intro = loop("joe_intro", "06_joe_intro.ogg", 98, 0.62),
  lyra_intro = loop("lyra_intro", "07_lyra_intro.ogg", 142, 0.62),
  stage1_opening = loop("stage1_opening", "08_stage1_opening.ogg", 124, 0.82, "bar"),
  stage1_pressure = loop("stage1_pressure", "09_stage1_pressure.ogg", 138, 0.82, "bar"),
  metronome_guardian = loop("metronome_guardian", "10_metronome_guardian.ogg", 136, 0.84, "immediate"),
  stage1_overload = loop("stage1_overload", "11_stage1_overload.ogg", 174, 0.80, "bar"),
  static_baron = loop("static_baron", "12_static_baron.ogg", 110, 0.84, "immediate"),
  first_press = loop("first_press", "13_first_press.ogg", 88, 0.60),
  dead_line_recovery = loop("dead_line_recovery", "14_dead_line_recovery.ogg", 90, 0.58),
  stage2_arrival = loop("stage2_arrival", "15_stage2_arrival.ogg", 126, 0.82, "bar"),
  stage2_escalation = loop("stage2_escalation", "16_stage2_escalation.ogg", 172, 0.80, "bar"),
  turntable_sentinel = loop("turntable_sentinel", "17_turntable_sentinel.ogg", 116, 0.84, "immediate"),
  stage2_overload = loop("stage2_overload", "18_stage2_overload.ogg", 176, 0.78, "bar"),
  grand_orchestrator_p1 = loop("grand_orchestrator_p1", "19_grand_orchestrator_p1.ogg", 132, 0.84, "immediate"),
  grand_orchestrator_final = loop(
    "grand_orchestrator_final", "20_grand_orchestrator_final.ogg",
    176, 0.84, "immediate"),
  level_up = loop("level_up", "21_level_up.ogg", 120, 0.72, "immediate"),
  evolution = loop("evolution", "22_evolution.ogg", 140, 0.74, "immediate"),
  low_health = loop("low_health", "23_low_health.ogg", 132, 0.36, "overlay"),
  pause = loop("pause", "24_pause.ogg", 92, 0.68, "immediate"),
  arsenal = loop("arsenal", "25_arsenal.ogg", 114, 0.72, "immediate"),
  admin = loop("admin", "26_admin.ogg", 120, 0.66, "immediate"),
  stage_clear = loop("stage_clear", "27_stage_clear.ogg", 124, 0.82),
  stage_clear_sting = {
    id = "stage_clear_sting",
    path = "assets/music/stage_clear_sting.ogg",
    bpm = 124,
    beats = 8,
    meter = 4,
    loop = false,
    gain = 0.86,
    transition = "one_shot",
  },
  victory_results = loop("victory_results", "28_victory_results.ogg", 118, 0.82),
  defeat_results = loop("defeat_results", "29_defeat_results.ogg", 84, 0.74, "immediate"),
  ending_teaser = loop("ending_teaser", "30_ending_teaser.ogg", 96, 0.58),
  world_tour_hub = loop("world_tour_hub", "31_world_tour_hub.ogg",
    110, 0.72, "crossfade", 128),
  world_funk_route = loop("world_funk_route", "32_world_funk_route.ogg",
    112, 0.78, "bar", 128),
  world_funk_boogie_tank = loop("world_funk_boogie_tank",
    "33_world_funk_boogie_tank.ogg", 118, 0.82, "immediate", 32),
  world_funk_mothership = loop("world_funk_mothership",
    "34_world_funk_mothership.ogg", 124, 0.84, "immediate", 64),
  world_soul_route = loop("world_soul_route", "35_world_soul_route.ogg",
    92, 0.78, "bar", 128),
  world_soul_organ_colossus = loop("world_soul_organ_colossus",
    "36_world_soul_organ_colossus.ogg", 100, 0.82, "immediate", 64),
  world_soul_velvet_titan = loop("world_soul_velvet_titan",
    "37_world_soul_velvet_titan.ogg", 108, 0.84, "immediate", 64),
  world_disco_route = loop("world_disco_route", "38_world_disco_route.ogg",
    122, 0.78, "bar", 128),
  world_disco_laser_conductor = loop("world_disco_laser_conductor",
    "39_world_disco_laser_conductor.ogg", 128, 0.82, "immediate", 64),
  world_disco_prism_monarch = loop("world_disco_prism_monarch",
    "40_world_disco_prism_monarch.ogg", 132, 0.84, "immediate", 64),
  world_house_route = loop("world_house_route", "41_world_house_route.ogg",
    124, 0.78, "bar", 128),
  world_house_pressure = loop("world_house_pressure",
    "42_world_house_pressure.ogg", 128, 0.82, "immediate", 64),
  world_house_kickdrum_constructor = loop("world_house_kickdrum_constructor",
    "43_world_house_kickdrum_constructor.ogg", 130, 0.84, "immediate", 64),
  world_electro_route = loop("world_electro_route", "44_world_electro_route.ogg",
    118, 0.78, "bar", 128),
  world_electro_pressure = loop("world_electro_pressure",
    "45_world_electro_pressure.ogg", 126, 0.82, "immediate", 64),
  world_electro_voltage_vandal = loop("world_electro_voltage_vandal",
    "46_world_electro_voltage_vandal.ogg", 132, 0.84, "immediate", 64),
  world_techno_route = loop("world_techno_route", "47_world_techno_route.ogg",
    132, 0.78, "bar", 128),
  world_techno_pressure = loop("world_techno_pressure",
    "48_world_techno_pressure.ogg", 138, 0.82, "immediate", 64),
  world_techno_loop_architect = loop("world_techno_loop_architect",
    "49_world_techno_loop_architect.ogg", 144, 0.84, "immediate", 64),
  world_cosmic_boogie_route = loop("world_cosmic_boogie_route",
    "50_world_cosmic_boogie_route.ogg", 116, 0.78, "bar", 128),
  world_cosmic_boogie_pressure = loop("world_cosmic_boogie_pressure",
    "51_world_cosmic_boogie_pressure.ogg", 124, 0.82, "immediate", 64),
  world_cosmic_boogie_celestial_selector = loop(
    "world_cosmic_boogie_celestial_selector",
    "52_world_cosmic_boogie_celestial_selector.ogg", 130, 0.84, "immediate", 64),
  world_soulful_garage_route = loop("world_soulful_garage_route",
    "53_world_soulful_garage_route.ogg", 132, 0.78, "bar", 128),
  world_soulful_garage_pressure = loop("world_soulful_garage_pressure",
    "54_world_soulful_garage_pressure.ogg", 136, 0.82, "immediate", 64),
  world_soulful_garage_night_shift_conductor = loop(
    "world_soulful_garage_night_shift_conductor",
    "55_world_soulful_garage_night_shift_conductor.ogg", 140, 0.84, "immediate", 64),
  world_future_funk_route = loop("world_future_funk_route",
    "56_world_future_funk_route.ogg", 116, 0.78, "bar", 128),
  world_future_funk_pressure = loop("world_future_funk_pressure",
    "57_world_future_funk_pressure.ogg", 124, 0.82, "immediate", 64),
  world_future_funk_recompiler = loop("world_future_funk_recompiler",
    "58_world_future_funk_recompiler.ogg", 132, 0.84, "immediate", 64),
}
