local function loop(id, path, bpm, gain, transition)
  return {
    id = id,
    path = "assets/music/" .. path,
    bpm = bpm,
    beats = 32,
    meter = 4,
    loop = true,
    gain = gain or 1,
    transition = transition or "crossfade",
  }
end

return {
  title = loop("title", "01_title.ogg", 112, 1.00),
  prologue_city = loop("prologue_city", "02_prologue_city.ogg", 92, 0.62),
  prologue_break = loop("prologue_break", "03_prologue_break.ogg", 100, 0.60),
  prologue_resolve = loop("prologue_resolve", "04_prologue_resolve.ogg", 116, 0.62),
  character_select = loop("character_select", "05_character_select.ogg", 120, 0.86),
  joe_intro = loop("joe_intro", "06_joe_intro.ogg", 98, 0.62),
  lyra_intro = loop("lyra_intro", "07_lyra_intro.ogg", 142, 0.62),
  stage1_opening = loop("stage1_opening", "08_stage1_opening.ogg", 124, 0.82, "bar"),
  stage1_pressure = loop("stage1_pressure", "09_stage1_pressure.ogg", 138, 0.82, "bar"),
  metronome_guardian = loop("metronome_guardian", "10_metronome_guardian.ogg", 136, 0.84, "immediate"),
  stage1_overload = loop("stage1_overload", "11_stage1_overload.ogg", 174, 0.80, "bar"),
  static_baron = loop("static_baron", "12_static_baron.ogg", 110, 0.84, "immediate"),
  first_press = loop("first_press", "13_first_press.ogg", 88, 0.60),
  dead_line_recovery = loop("dead_line_recovery", "14_dead_line_recovery.ogg", 90, 0.58),
  stage2_arrival = loop("stage2_arrival", "15_stage2_arrival.ogg", 126, 0.82, "bar"),
  stage2_escalation = loop("stage2_escalation", "16_stage2_escalation.ogg", 172, 0.80, "bar"),
  turntable_sentinel = loop("turntable_sentinel", "17_turntable_sentinel.ogg", 116, 0.84, "immediate"),
  stage2_overload = loop("stage2_overload", "18_stage2_overload.ogg", 176, 0.78, "bar"),
  grand_orchestrator_p1 = loop("grand_orchestrator_p1", "19_grand_orchestrator_p1.ogg", 132, 0.84, "immediate"),
  grand_orchestrator_final = loop(
    "grand_orchestrator_final", "20_grand_orchestrator_final.ogg",
    176, 0.84, "immediate"),
  level_up = loop("level_up", "21_level_up.ogg", 120, 0.72, "immediate"),
  evolution = loop("evolution", "22_evolution.ogg", 140, 0.74, "immediate"),
  low_health = loop("low_health", "23_low_health.ogg", 132, 0.36, "overlay"),
  pause = loop("pause", "24_pause.ogg", 92, 0.68, "immediate"),
  arsenal = loop("arsenal", "25_arsenal.ogg", 114, 0.72, "immediate"),
  admin = loop("admin", "26_admin.ogg", 120, 0.66, "immediate"),
  stage_clear = loop("stage_clear", "27_stage_clear.ogg", 124, 0.82),
  stage_clear_sting = {
    id = "stage_clear_sting",
    path = "assets/music/stage_clear_sting.ogg",
    bpm = 124,
    beats = 8,
    meter = 4,
    loop = false,
    gain = 0.86,
    transition = "one_shot",
  },
  victory_results = loop("victory_results", "28_victory_results.ogg", 118, 0.82),
  defeat_results = loop("defeat_results", "29_defeat_results.ogg", 84, 0.74, "immediate"),
  ending_teaser = loop("ending_teaser", "30_ending_teaser.ogg", 96, 0.58),
}
