-- Weapon definitions. Logic never reads `name` — only `id`.
-- cooldown is always SECONDS between activations ("rate" terminology banned).
-- The launch roster keeps explicit rows. Expansion weapons use the same
-- deterministic rank curve helper to keep a 16-weapon balance pass readable.

local function ranked(opts)
  local result = {}
  for level = 1, 10 do
    local step = level - 1
    result[level] = {
      damage = math.floor(opts.damage * (1 + step * opts.damage_growth) + 0.5),
      cooldown = math.max(opts.min_cooldown, opts.cooldown - step * opts.cooldown_step),
      count = opts.count + math.floor(step / opts.count_every),
      speed = opts.speed + step * (opts.speed_step or 0),
      size = opts.size + math.floor(step / (opts.size_every or 20)),
      lifetime = opts.lifetime + step * (opts.lifetime_step or 0),
      spread = math.max(0, opts.spread - step * (opts.spread_step or 0)),
      pierce = (opts.pierce or 0) + math.floor(step / (opts.pierce_every or 20)),
      knockback = (opts.knockback or 8) + step * (opts.knockback_step or 0),
    }
  end
  return result
end

return {
  kazoo_pistol = {
    id          = "kazoo_pistol",
    name        = "Kazoo Pistol",
    description = "Joe's trusty starter. Fires a single buzzing note.",
    archetype   = "projectile",
    role        = "Balanced starter",
    pattern     = "aimed",
    rarity      = "common",
    icon        = { col = 1, row = 1 },
    projectile_color = { 1.0, 0.82, 0.24, 1 },
    max_level   = 10,
    levels = {
      { damage = 10, cooldown = 0.80, count = 1, speed = 420, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 12, cooldown = 0.72, count = 1, speed = 420, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 14, cooldown = 0.65, count = 2, speed = 420, size = 6, lifetime = 1.5, spread = 8 },
      { damage = 16, cooldown = 0.62, count = 2, speed = 440, size = 6, lifetime = 1.6, spread = 7 },
      { damage = 18, cooldown = 0.58, count = 2, speed = 450, size = 6, lifetime = 1.6, spread = 7 },
      { damage = 20, cooldown = 0.55, count = 2, speed = 460, size = 7, lifetime = 1.7, spread = 6 },
      { damage = 22, cooldown = 0.52, count = 3, speed = 470, size = 7, lifetime = 1.7, spread = 10 },
      { damage = 24, cooldown = 0.49, count = 3, speed = 480, size = 7, lifetime = 1.8, spread = 9 },
      { damage = 26, cooldown = 0.46, count = 3, speed = 490, size = 8, lifetime = 1.8, spread = 8 },
      { damage = 28, cooldown = 0.43, count = 3, speed = 500, size = 8, lifetime = 1.9, spread = 8 },
    },
  },

  bass_drop = {
    id          = "bass_drop",
    name        = "Bass Drop",
    description = "A slow, heavy note with high damage and natural pierce.",
    archetype   = "projectile",
    role        = "Heavy piercer",
    pattern     = "aimed",
    rarity      = "uncommon",
    icon        = { col = 2, row = 1 },
    projectile_color = { 0.70, 0.36, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 20, cooldown = 1.20, count = 1, speed = 330, size = 11, lifetime = 2.0, spread = 0, pierce = 1 },
      { damage = 24, cooldown = 1.12, count = 1, speed = 340, size = 11, lifetime = 2.0, spread = 0, pierce = 1 },
      { damage = 28, cooldown = 1.05, count = 1, speed = 350, size = 12, lifetime = 2.1, spread = 0, pierce = 2 },
      { damage = 33, cooldown = 0.98, count = 1, speed = 360, size = 12, lifetime = 2.1, spread = 0, pierce = 2 },
      { damage = 38, cooldown = 0.92, count = 2, speed = 365, size = 12, lifetime = 2.2, spread = 7, pierce = 2 },
      { damage = 44, cooldown = 0.86, count = 2, speed = 370, size = 13, lifetime = 2.2, spread = 7, pierce = 2 },
      { damage = 50, cooldown = 0.80, count = 2, speed = 380, size = 13, lifetime = 2.3, spread = 6, pierce = 3 },
      { damage = 56, cooldown = 0.75, count = 2, speed = 390, size = 14, lifetime = 2.3, spread = 6, pierce = 3 },
      { damage = 63, cooldown = 0.70, count = 2, speed = 400, size = 14, lifetime = 2.4, spread = 5, pierce = 4 },
      { damage = 72, cooldown = 0.65, count = 3, speed = 410, size = 15, lifetime = 2.5, spread = 8, pierce = 4 },
    },
  },

  cymbal_slicer = {
    id          = "cymbal_slicer",
    name        = "Cymbal Slicer",
    description = "Fast cutting notes that fan across nearby targets.",
    archetype   = "spread",
    role        = "Wide spread",
    pattern     = "aimed",
    rarity      = "common",
    icon        = { col = 3, row = 1 },
    projectile_color = { 1.0, 0.62, 0.16, 1 },
    max_level   = 10,
    levels = {
      { damage = 7, cooldown = 0.52, count = 2, speed = 520, size = 5, lifetime = 1.2, spread = 13 },
      { damage = 8, cooldown = 0.49, count = 2, speed = 530, size = 5, lifetime = 1.2, spread = 12 },
      { damage = 9, cooldown = 0.46, count = 3, speed = 540, size = 5, lifetime = 1.3, spread = 11 },
      { damage = 10, cooldown = 0.43, count = 3, speed = 550, size = 6, lifetime = 1.3, spread = 10 },
      { damage = 12, cooldown = 0.40, count = 3, speed = 560, size = 6, lifetime = 1.4, spread = 10 },
      { damage = 14, cooldown = 0.37, count = 4, speed = 570, size = 6, lifetime = 1.4, spread = 9 },
      { damage = 16, cooldown = 0.34, count = 4, speed = 580, size = 6, lifetime = 1.5, spread = 9 },
      { damage = 18, cooldown = 0.31, count = 4, speed = 590, size = 7, lifetime = 1.5, spread = 8 },
      { damage = 20, cooldown = 0.28, count = 5, speed = 600, size = 7, lifetime = 1.6, spread = 8 },
      { damage = 23, cooldown = 0.25, count = 5, speed = 620, size = 7, lifetime = 1.7, spread = 7, pierce = 1 },
    },
  },

  feedback_loop = {
    id          = "feedback_loop",
    name        = "Feedback Loop",
    description = "A focused sustained tone that accelerates as it ranks up.",
    archetype   = "projectile",
    role        = "Rapid focus",
    pattern     = "aimed",
    rarity      = "uncommon",
    icon        = { col = 4, row = 1 },
    projectile_color = { 0.28, 0.92, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 9, cooldown = 0.68, count = 1, speed = 470, size = 7, lifetime = 1.8, spread = 0 },
      { damage = 11, cooldown = 0.62, count = 1, speed = 480, size = 7, lifetime = 1.8, spread = 0 },
      { damage = 13, cooldown = 0.57, count = 2, speed = 490, size = 7, lifetime = 1.9, spread = 4 },
      { damage = 15, cooldown = 0.52, count = 2, speed = 500, size = 7, lifetime = 1.9, spread = 4 },
      { damage = 17, cooldown = 0.47, count = 2, speed = 510, size = 8, lifetime = 2.0, spread = 3 },
      { damage = 19, cooldown = 0.42, count = 2, speed = 520, size = 8, lifetime = 2.0, spread = 3, pierce = 1 },
      { damage = 21, cooldown = 0.38, count = 3, speed = 530, size = 8, lifetime = 2.1, spread = 5, pierce = 1 },
      { damage = 23, cooldown = 0.34, count = 3, speed = 540, size = 8, lifetime = 2.1, spread = 4, pierce = 1 },
      { damage = 26, cooldown = 0.30, count = 3, speed = 550, size = 9, lifetime = 2.2, spread = 4, pierce = 2 },
      { damage = 30, cooldown = 0.26, count = 4, speed = 570, size = 9, lifetime = 2.3, spread = 5, pierce = 2 },
    },
  },

  drum_circle = {
    id          = "drum_circle",
    name        = "Drum Circle",
    description = "Throws a complete ring of percussion around Joe.",
    archetype   = "spread",
    role        = "Radial control",
    pattern     = "radial",
    rarity      = "rare",
    icon        = { col = 1, row = 2 },
    projectile_color = { 0.28, 1.0, 0.70, 1 },
    max_level   = 10,
    levels = {
      { damage = 7, cooldown = 1.45, count = 6, speed = 330, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 8, cooldown = 1.36, count = 6, speed = 340, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 9, cooldown = 1.28, count = 8, speed = 350, size = 6, lifetime = 1.6, spread = 0 },
      { damage = 10, cooldown = 1.20, count = 8, speed = 360, size = 7, lifetime = 1.6, spread = 0 },
      { damage = 12, cooldown = 1.12, count = 8, speed = 370, size = 7, lifetime = 1.7, spread = 0, pierce = 1 },
      { damage = 14, cooldown = 1.04, count = 10, speed = 380, size = 7, lifetime = 1.7, spread = 0, pierce = 1 },
      { damage = 16, cooldown = 0.96, count = 10, speed = 390, size = 8, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 18, cooldown = 0.88, count = 12, speed = 400, size = 8, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 21, cooldown = 0.80, count = 12, speed = 410, size = 8, lifetime = 1.9, spread = 0, pierce = 2 },
      { damage = 24, cooldown = 0.72, count = 14, speed = 420, size = 9, lifetime = 2.0, spread = 0, pierce = 2 },
    },
  },

  trumpet_burst = {
    id          = "trumpet_burst",
    name        = "Trumpet Burst",
    description = "A tight, forceful cone of brass notes with strong knockback.",
    archetype   = "spread",
    role        = "Close burst",
    pattern     = "aimed",
    rarity      = "common",
    icon        = { col = 2, row = 2 },
    projectile_color = { 1.0, 0.34, 0.28, 1 },
    max_level   = 10,
    levels = {
      { damage = 11, cooldown = 0.92, count = 3, speed = 470, size = 7, lifetime = 1.0, spread = 7, knockback = 16 },
      { damage = 13, cooldown = 0.86, count = 3, speed = 480, size = 7, lifetime = 1.0, spread = 7, knockback = 17 },
      { damage = 15, cooldown = 0.80, count = 4, speed = 490, size = 7, lifetime = 1.1, spread = 6, knockback = 18 },
      { damage = 17, cooldown = 0.74, count = 4, speed = 500, size = 8, lifetime = 1.1, spread = 6, knockback = 19 },
      { damage = 20, cooldown = 0.68, count = 5, speed = 510, size = 8, lifetime = 1.2, spread = 6, knockback = 20 },
      { damage = 23, cooldown = 0.62, count = 5, speed = 520, size = 8, lifetime = 1.2, spread = 5, knockback = 21 },
      { damage = 26, cooldown = 0.57, count = 6, speed = 530, size = 9, lifetime = 1.3, spread = 5, knockback = 22 },
      { damage = 29, cooldown = 0.52, count = 6, speed = 540, size = 9, lifetime = 1.3, spread = 5, knockback = 23 },
      { damage = 33, cooldown = 0.47, count = 7, speed = 550, size = 9, lifetime = 1.4, spread = 4, knockback = 24 },
      { damage = 38, cooldown = 0.42, count = 8, speed = 570, size = 10, lifetime = 1.5, spread = 4, knockback = 26 },
    },
  },

  vinyl_scratch = {
    id          = "vinyl_scratch",
    name        = "Vinyl Scratch",
    description = "Alternates cutting lanes to rake through packed crowds.",
    archetype   = "spread",
    role        = "Lane cutter",
    pattern     = "cross",
    rarity      = "uncommon",
    icon        = { col = 3, row = 2 },
    projectile_color = { 0.78, 0.30, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 13, cooldown = 0.88, count = 2, speed = 500, size = 7, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 15, cooldown = 0.82, count = 2, speed = 510, size = 7, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 17, cooldown = 0.76, count = 3, speed = 520, size = 7, lifetime = 1.9, spread = 0, pierce = 1 },
      { damage = 20, cooldown = 0.70, count = 3, speed = 530, size = 8, lifetime = 1.9, spread = 0, pierce = 2 },
      { damage = 23, cooldown = 0.64, count = 4, speed = 540, size = 8, lifetime = 2.0, spread = 0, pierce = 2 },
      { damage = 26, cooldown = 0.58, count = 4, speed = 550, size = 8, lifetime = 2.0, spread = 0, pierce = 2 },
      { damage = 30, cooldown = 0.52, count = 5, speed = 560, size = 9, lifetime = 2.1, spread = 0, pierce = 2 },
      { damage = 34, cooldown = 0.47, count = 5, speed = 570, size = 9, lifetime = 2.1, spread = 0, pierce = 3 },
      { damage = 39, cooldown = 0.42, count = 6, speed = 580, size = 9, lifetime = 2.2, spread = 0, pierce = 3 },
      { damage = 45, cooldown = 0.37, count = 6, speed = 600, size = 10, lifetime = 2.3, spread = 0, pierce = 4 },
    },
  },

  synth_wave = {
    id          = "synth_wave",
    name        = "Synth Wave",
    description = "Projects a slow wall of oversized neon notes.",
    archetype   = "spread",
    role        = "Area wall",
    pattern     = "wall",
    rarity      = "rare",
    icon        = { col = 4, row = 2 },
    projectile_color = { 0.20, 0.96, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 16, cooldown = 1.30, count = 3, speed = 250, size = 14, lifetime = 2.4, spread = 18, pierce = 1 },
      { damage = 19, cooldown = 1.22, count = 3, speed = 260, size = 14, lifetime = 2.4, spread = 17, pierce = 1 },
      { damage = 22, cooldown = 1.14, count = 4, speed = 270, size = 15, lifetime = 2.5, spread = 16, pierce = 1 },
      { damage = 25, cooldown = 1.06, count = 4, speed = 280, size = 15, lifetime = 2.5, spread = 15, pierce = 2 },
      { damage = 29, cooldown = 0.98, count = 5, speed = 290, size = 16, lifetime = 2.6, spread = 14, pierce = 2 },
      { damage = 33, cooldown = 0.90, count = 5, speed = 300, size = 16, lifetime = 2.6, spread = 13, pierce = 2 },
      { damage = 38, cooldown = 0.82, count = 6, speed = 310, size = 17, lifetime = 2.7, spread = 12, pierce = 2 },
      { damage = 43, cooldown = 0.75, count = 6, speed = 320, size = 17, lifetime = 2.7, spread = 11, pierce = 3 },
      { damage = 49, cooldown = 0.68, count = 7, speed = 330, size = 18, lifetime = 2.8, spread = 10, pierce = 3 },
      { damage = 56, cooldown = 0.60, count = 8, speed = 340, size = 19, lifetime = 3.0, spread = 9, pierce = 4 },
    },
  },

  triangle_tracer = {
    id = "triangle_tracer",
    name = "Triangle Tracer",
    description = "Rapid silver pings drill through a precise target line.",
    archetype = "projectile",
    role = "Rapid piercer",
    pattern = "aimed",
    rarity = "common",
    icon = { atlas = "base2", col = 1, row = 1 },
    projectile_color = { 0.45, 0.90, 1.0, 1 },
    max_level = 10,
    levels = ranked({
      damage = 8, damage_growth = 0.13, cooldown = 0.42,
      cooldown_step = 0.018, min_cooldown = 0.20, count = 1,
      count_every = 4, speed = 650, speed_step = 12, size = 4,
      lifetime = 1.6, spread = 2, pierce = 1, pierce_every = 3,
    }),
  },

  cello_lance = {
    id = "cello_lance",
    name = "Cello Lance",
    description = "A deliberate string thrust with extreme damage and pierce.",
    archetype = "projectile",
    role = "Precision sniper",
    pattern = "aimed",
    rarity = "rare",
    icon = { atlas = "base2", col = 2, row = 1 },
    projectile_color = { 1.0, 0.55, 0.16, 1 },
    max_level = 10,
    levels = ranked({
      damage = 42, damage_growth = 0.17, cooldown = 1.65,
      cooldown_step = 0.07, min_cooldown = 0.82, count = 1,
      count_every = 7, speed = 760, speed_step = 8, size = 8,
      size_every = 4, lifetime = 2.4, spread = 0, pierce = 3,
      pierce_every = 2, knockback = 20, knockback_step = 1,
    }),
  },

  maraca_orbit = {
    id = "maraca_orbit",
    name = "Maraca Orbit",
    description = "Rotating percussion spirals continuously sweep nearby space.",
    archetype = "spread",
    role = "Spiral defense",
    pattern = "spiral",
    rarity = "uncommon",
    icon = { atlas = "base2", col = 3, row = 1 },
    projectile_color = { 0.32, 1.0, 0.62, 1 },
    max_level = 10,
    levels = ranked({
      damage = 8, damage_growth = 0.12, cooldown = 0.86,
      cooldown_step = 0.035, min_cooldown = 0.44, count = 3,
      count_every = 2, speed = 330, speed_step = 8, size = 6,
      lifetime = 2.2, lifetime_step = 0.04, spread = 0, pierce = 0,
      pierce_every = 4,
    }),
  },

  tuning_fork = {
    id = "tuning_fork",
    name = "Tuning Fork",
    description = "Matched notes fire forward and backward through encirclement.",
    archetype = "spread",
    role = "Front-back lane",
    pattern = "front_back",
    rarity = "common",
    icon = { atlas = "base2", col = 4, row = 1 },
    projectile_color = { 0.32, 0.72, 1.0, 1 },
    max_level = 10,
    levels = ranked({
      damage = 14, damage_growth = 0.14, cooldown = 0.82,
      cooldown_step = 0.032, min_cooldown = 0.42, count = 2,
      count_every = 3, speed = 510, speed_step = 10, size = 7,
      lifetime = 1.9, spread = 7, spread_step = 0.3, pierce = 1,
      pierce_every = 4,
    }),
  },

  keytar_chord = {
    id = "keytar_chord",
    name = "Keytar Chord",
    description = "A broad harmonic wall advances slowly through whole crowds.",
    archetype = "spread",
    role = "Broad formation",
    pattern = "wall",
    rarity = "uncommon",
    icon = { atlas = "base2", col = 1, row = 2 },
    projectile_color = { 0.44, 0.42, 1.0, 1 },
    max_level = 10,
    levels = ranked({
      damage = 12, damage_growth = 0.15, cooldown = 1.08,
      cooldown_step = 0.04, min_cooldown = 0.56, count = 4,
      count_every = 3, speed = 285, speed_step = 7, size = 13,
      size_every = 3, lifetime = 2.8, spread = 15,
      spread_step = 0.45, pierce = 1, pierce_every = 3,
    }),
  },

  bell_tower = {
    id = "bell_tower",
    name = "Bell Tower",
    description = "Slow bronze tolls erupt outward with crushing knockback.",
    archetype = "spread",
    role = "Heavy nova",
    pattern = "radial",
    rarity = "rare",
    icon = { atlas = "base2", col = 2, row = 2 },
    projectile_color = { 1.0, 0.76, 0.22, 1 },
    max_level = 10,
    levels = ranked({
      damage = 24, damage_growth = 0.16, cooldown = 1.85,
      cooldown_step = 0.075, min_cooldown = 0.92, count = 4,
      count_every = 2, speed = 260, speed_step = 8, size = 12,
      size_every = 4, lifetime = 2.3, spread = 0, pierce = 1,
      pierce_every = 3, knockback = 28, knockback_step = 2,
    }),
  },

  tape_repeater = {
    id = "tape_repeater",
    name = "Tape Repeater",
    description = "Recorded attacks echo from alternating side lanes.",
    archetype = "spread",
    role = "Side-lane repeat",
    pattern = "sideways",
    rarity = "uncommon",
    icon = { atlas = "base2", col = 3, row = 2 },
    projectile_color = { 0.38, 1.0, 0.82, 1 },
    max_level = 10,
    levels = ranked({
      damage = 10, damage_growth = 0.15, cooldown = 0.64,
      cooldown_step = 0.025, min_cooldown = 0.32, count = 2,
      count_every = 3, speed = 470, speed_step = 9, size = 6,
      lifetime = 2.0, spread = 6, spread_step = 0.25, pierce = 1,
      pierce_every = 3,
    }),
  },

  laser_harp = {
    id = "laser_harp",
    name = "Laser Harp",
    description = "A brilliant fan of fast strings rewards close positioning.",
    archetype = "spread",
    role = "Rapid cone",
    pattern = "aimed",
    rarity = "rare",
    icon = { atlas = "base2", col = 4, row = 2 },
    projectile_color = { 0.26, 0.94, 1.0, 1 },
    max_level = 10,
    levels = ranked({
      damage = 9, damage_growth = 0.14, cooldown = 0.48,
      cooldown_step = 0.018, min_cooldown = 0.24, count = 4,
      count_every = 2, speed = 620, speed_step = 11, size = 5,
      lifetime = 1.35, spread = 10, spread_step = 0.4, pierce = 0,
      pierce_every = 4,
    }),
  },

  brass_barrage = {
    id          = "brass_barrage",
    name        = "Brass Barrage",
    description = "Kazoo and Breath Control fuse into a piercing three-note burst.",
    archetype   = "spread",
    role        = "Kazoo fusion",
    pattern     = "aimed",
    rarity      = "evolved",
    icon        = { atlas = "evolved", col = 1, row = 1 },
    projectile_color = { 1.0, 0.72, 0.18, 1 },
    max_level   = 1,
    evolved     = true,
    levels = {
      {
        damage = 42,
        cooldown = 0.36,
        count = 3,
        speed = 560,
        size = 9,
        lifetime = 2.0,
        spread = 12,
        pierce = 3,
      },
    },
  },

  improvised_solo = {
    id          = "improvised_solo",
    name        = "Improvised Solo",
    description = "Feedback Loop and Overdrive fused into an accelerating electric phrase.",
    archetype   = "projectile",
    role        = "Feedback fusion",
    pattern     = "front_back",
    rarity      = "evolved",
    icon        = { atlas = "evolved", col = 4, row = 1 },
    projectile_color = { 0.38, 1.0, 0.76, 1 },
    max_level   = 1,
    evolved     = true,
    levels = {
      {
        damage = 34,
        cooldown = 0.28,
        count = 2,
        speed = 620,
        size = 8,
        lifetime = 2.1,
        spread = 5,
        pierce = 2,
      },
    },
  },

  subwoofer_supernova = {
    id = "subwoofer_supernova",
    name = "Subwoofer Supernova",
    description = "Bass Drop and Power Amplifier collapse into a piercing shockwave.",
    archetype = "spread",
    role = "Bass fusion",
    pattern = "radial",
    rarity = "evolved",
    icon = { atlas = "evolved", col = 2, row = 1 },
    projectile_color = { 0.82, 0.52, 1.0, 1 },
    max_level = 1,
    evolved = true,
    levels = {
      { damage = 76, cooldown = 0.58, count = 12, speed = 410, size = 17,
        lifetime = 2.8, spread = 0, pierce = 5, knockback = 32 },
    },
  },

  orbital_ovation = {
    id = "orbital_ovation",
    name = "Orbital Ovation",
    description = "Cymbal Slicer and Quickstep become a relentless golden orbit.",
    archetype = "spread",
    role = "Cymbal fusion",
    pattern = "spiral",
    rarity = "evolved",
    icon = { atlas = "evolved", col = 3, row = 1 },
    projectile_color = { 1.0, 0.86, 0.32, 1 },
    max_level = 1,
    evolved = true,
    levels = {
      { damage = 31, cooldown = 0.18, count = 8, speed = 610, size = 9,
        lifetime = 2.1, spread = 0, pierce = 4, knockback = 14 },
    },
  },

  thunderhead_ensemble = {
    id = "thunderhead_ensemble",
    name = "Thunderhead Ensemble",
    description = "Drum Circle and Encore merge into a restorative thunder nova.",
    archetype = "spread",
    role = "Drum fusion",
    pattern = "radial",
    rarity = "evolved",
    icon = { atlas = "evolved", col = 1, row = 2 },
    projectile_color = { 1.0, 0.30, 0.38, 1 },
    max_level = 1,
    evolved = true,
    levels = {
      { damage = 48, cooldown = 0.48, count = 16, speed = 450, size = 12,
        lifetime = 2.4, spread = 0, pierce = 3, knockback = 24 },
    },
  },

  golden_fortissimo = {
    id = "golden_fortissimo",
    name = "Golden Fortissimo",
    description = "Trumpet Burst and Safety Vest form an armored brass barrage.",
    archetype = "spread",
    role = "Trumpet fusion",
    pattern = "aimed",
    rarity = "evolved",
    icon = { atlas = "evolved", col = 2, row = 2 },
    projectile_color = { 1.0, 0.82, 0.24, 1 },
    max_level = 1,
    evolved = true,
    levels = {
      { damage = 58, cooldown = 0.30, count = 10, speed = 650, size = 11,
        lifetime = 1.8, spread = 4, pierce = 3, knockback = 40 },
    },
  },

  gravity_groove = {
    id = "gravity_groove",
    name = "Gravity Groove",
    description = "Vinyl Scratch and Pickup Magnet cut four gravitational lanes.",
    archetype = "spread",
    role = "Vinyl fusion",
    pattern = "cross",
    rarity = "evolved",
    icon = { atlas = "evolved", col = 3, row = 2 },
    projectile_color = { 0.72, 0.38, 1.0, 1 },
    max_level = 1,
    evolved = true,
    levels = {
      { damage = 62, cooldown = 0.34, count = 8, speed = 590, size = 12,
        lifetime = 2.8, spread = 0, pierce = 6, knockback = 18 },
    },
  },

  neon_crescendo = {
    id = "neon_crescendo",
    name = "Neon Crescendo",
    description = "Synth Wave and Echo Chamber become a repeating iridescent wall.",
    archetype = "spread",
    role = "Synth fusion",
    pattern = "wall",
    rarity = "evolved",
    icon = { atlas = "evolved", col = 4, row = 2 },
    projectile_color = { 0.34, 1.0, 0.92, 1 },
    max_level = 1,
    evolved = true,
    levels = {
      { damage = 68, cooldown = 0.52, count = 12, speed = 390, size = 21,
        lifetime = 3.2, spread = 7, pierce = 5, knockback = 20 },
    },
  },

  prismatic_triangle = {
    id = "prismatic_triangle", name = "Prismatic Triangle",
    description = "Triangle Tracer refracts into three piercing spectral lanes.",
    archetype = "spread", role = "Triangle fusion", pattern = "cross",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 1, row = 1 },
    projectile_color = { 0.48, 0.96, 1.0, 1 }, max_level = 1,
    levels = { { damage = 64, cooldown = 0.34, count = 9, speed = 690,
      size = 10, lifetime = 2.5, spread = 0, pierce = 6, knockback = 18 } },
  },

  velvet_impaler = {
    id = "velvet_impaler", name = "Velvet Impaler",
    description = "Cello Lance becomes a sustained armored spear line.",
    archetype = "projectile", role = "Cello fusion", pattern = "aimed",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 2, row = 1 },
    projectile_color = { 0.42, 0.72, 1.0, 1 }, max_level = 1,
    levels = { { damage = 92, cooldown = 0.42, count = 3, speed = 760,
      size = 14, lifetime = 3.0, spread = 3, pierce = 9, knockback = 34 } },
  },

  carnival_superorbit = {
    id = "carnival_superorbit", name = "Carnival Superorbit",
    description = "Maraca Orbit expands into a relentless carnival halo.",
    archetype = "spread", role = "Maraca fusion", pattern = "spiral",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 3, row = 1 },
    projectile_color = { 1.0, 0.42, 0.72, 1 }, max_level = 1,
    levels = { { damage = 42, cooldown = 0.19, count = 12, speed = 600,
      size = 10, lifetime = 2.8, spread = 0, pierce = 5, knockback = 16 } },
  },

  resonance_rupture = {
    id = "resonance_rupture", name = "Resonance Rupture",
    description = "Tuning Fork tears synchronized lanes through the arena.",
    archetype = "spread", role = "Tuning fork fusion", pattern = "front_back",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 4, row = 1 },
    projectile_color = { 0.52, 0.86, 1.0, 1 }, max_level = 1,
    levels = { { damage = 78, cooldown = 0.30, count = 8, speed = 720,
      size = 12, lifetime = 3.2, spread = 5, pierce = 8, knockback = 28 } },
  },

  stadium_keytar = {
    id = "stadium_keytar", name = "Stadium Keytar",
    description = "Keytar Chord fills the stage with a championship wall of sound.",
    archetype = "spread", role = "Keytar fusion", pattern = "wall",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 1, row = 2 },
    projectile_color = { 0.62, 0.44, 1.0, 1 }, max_level = 1,
    levels = { { damage = 72, cooldown = 0.50, count = 14, speed = 430,
      size = 20, lifetime = 3.4, spread = 8, pierce = 6, knockback = 22 } },
  },

  cathedral_overdrive = {
    id = "cathedral_overdrive", name = "Cathedral Overdrive",
    description = "Bell Tower and armor toll an arena-clearing overdrive nova.",
    archetype = "spread", role = "Bell fusion", pattern = "radial",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 2, row = 2 },
    projectile_color = { 1.0, 0.76, 0.22, 1 }, max_level = 1,
    levels = { { damage = 105, cooldown = 0.70, count = 18, speed = 470,
      size = 16, lifetime = 3.0, spread = 0, pierce = 7, knockback = 52 } },
  },

  infinite_mixtape = {
    id = "infinite_mixtape", name = "Infinite Mixtape",
    description = "Tape Repeater loops luminous side lanes without an ending.",
    archetype = "spread", role = "Tape fusion", pattern = "sideways",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 3, row = 2 },
    projectile_color = { 0.34, 1.0, 0.82, 1 }, max_level = 1,
    levels = { { damage = 54, cooldown = 0.20, count = 10, speed = 680,
      size = 10, lifetime = 3.2, spread = 4, pierce = 6, knockback = 18 } },
  },

  aurora_harp = {
    id = "aurora_harp", name = "Aurora Harp",
    description = "Laser Harp fans celestial strings across the whole front line.",
    archetype = "spread", role = "Laser harp fusion", pattern = "aimed",
    rarity = "evolved", evolved = true,
    icon = { atlas = "evolved2", col = 4, row = 2 },
    projectile_color = { 0.32, 0.96, 1.0, 1 }, max_level = 1,
    levels = { { damage = 48, cooldown = 0.16, count = 12, speed = 820,
      size = 8, lifetime = 2.0, spread = 12, pierce = 4, knockback = 14 } },
  },
}
