-- Weapon definitions. Logic never reads `name` — only `id`.
-- cooldown is always SECONDS between activations ("rate" terminology banned).
-- Stats are explicit per-level rows so balance is auditable at a glance.

return {
  kazoo_pistol = {
    id          = "kazoo_pistol",
    name        = "Kazoo Pistol",
    description = "Joe's trusty starter. Fires a single buzzing note.",
    archetype   = "projectile",
    role        = "Balanced starter",
    pattern     = "aimed",
    rarity      = "common",
    icon        = { col = 1, row = 1 },
    projectile_color = { 1.0, 0.82, 0.24, 1 },
    max_level   = 10,
    levels = {
      { damage = 10, cooldown = 0.80, count = 1, speed = 420, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 12, cooldown = 0.72, count = 1, speed = 420, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 14, cooldown = 0.65, count = 2, speed = 420, size = 6, lifetime = 1.5, spread = 8 },
      { damage = 16, cooldown = 0.62, count = 2, speed = 440, size = 6, lifetime = 1.6, spread = 7 },
      { damage = 18, cooldown = 0.58, count = 2, speed = 450, size = 6, lifetime = 1.6, spread = 7 },
      { damage = 20, cooldown = 0.55, count = 2, speed = 460, size = 7, lifetime = 1.7, spread = 6 },
      { damage = 22, cooldown = 0.52, count = 3, speed = 470, size = 7, lifetime = 1.7, spread = 10 },
      { damage = 24, cooldown = 0.49, count = 3, speed = 480, size = 7, lifetime = 1.8, spread = 9 },
      { damage = 26, cooldown = 0.46, count = 3, speed = 490, size = 8, lifetime = 1.8, spread = 8 },
      { damage = 28, cooldown = 0.43, count = 3, speed = 500, size = 8, lifetime = 1.9, spread = 8 },
    },
  },

  bass_drop = {
    id          = "bass_drop",
    name        = "Bass Drop",
    description = "A slow, heavy note with high damage and natural pierce.",
    archetype   = "projectile",
    role        = "Heavy piercer",
    pattern     = "aimed",
    rarity      = "uncommon",
    icon        = { col = 2, row = 1 },
    projectile_color = { 0.70, 0.36, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 20, cooldown = 1.20, count = 1, speed = 330, size = 11, lifetime = 2.0, spread = 0, pierce = 1 },
      { damage = 24, cooldown = 1.12, count = 1, speed = 340, size = 11, lifetime = 2.0, spread = 0, pierce = 1 },
      { damage = 28, cooldown = 1.05, count = 1, speed = 350, size = 12, lifetime = 2.1, spread = 0, pierce = 2 },
      { damage = 33, cooldown = 0.98, count = 1, speed = 360, size = 12, lifetime = 2.1, spread = 0, pierce = 2 },
      { damage = 38, cooldown = 0.92, count = 2, speed = 365, size = 12, lifetime = 2.2, spread = 7, pierce = 2 },
      { damage = 44, cooldown = 0.86, count = 2, speed = 370, size = 13, lifetime = 2.2, spread = 7, pierce = 2 },
      { damage = 50, cooldown = 0.80, count = 2, speed = 380, size = 13, lifetime = 2.3, spread = 6, pierce = 3 },
      { damage = 56, cooldown = 0.75, count = 2, speed = 390, size = 14, lifetime = 2.3, spread = 6, pierce = 3 },
      { damage = 63, cooldown = 0.70, count = 2, speed = 400, size = 14, lifetime = 2.4, spread = 5, pierce = 4 },
      { damage = 72, cooldown = 0.65, count = 3, speed = 410, size = 15, lifetime = 2.5, spread = 8, pierce = 4 },
    },
  },

  cymbal_slicer = {
    id          = "cymbal_slicer",
    name        = "Cymbal Slicer",
    description = "Fast cutting notes that fan across nearby targets.",
    archetype   = "spread",
    role        = "Wide spread",
    pattern     = "aimed",
    rarity      = "common",
    icon        = { col = 3, row = 1 },
    projectile_color = { 1.0, 0.62, 0.16, 1 },
    max_level   = 10,
    levels = {
      { damage = 7, cooldown = 0.52, count = 2, speed = 520, size = 5, lifetime = 1.2, spread = 13 },
      { damage = 8, cooldown = 0.49, count = 2, speed = 530, size = 5, lifetime = 1.2, spread = 12 },
      { damage = 9, cooldown = 0.46, count = 3, speed = 540, size = 5, lifetime = 1.3, spread = 11 },
      { damage = 10, cooldown = 0.43, count = 3, speed = 550, size = 6, lifetime = 1.3, spread = 10 },
      { damage = 12, cooldown = 0.40, count = 3, speed = 560, size = 6, lifetime = 1.4, spread = 10 },
      { damage = 14, cooldown = 0.37, count = 4, speed = 570, size = 6, lifetime = 1.4, spread = 9 },
      { damage = 16, cooldown = 0.34, count = 4, speed = 580, size = 6, lifetime = 1.5, spread = 9 },
      { damage = 18, cooldown = 0.31, count = 4, speed = 590, size = 7, lifetime = 1.5, spread = 8 },
      { damage = 20, cooldown = 0.28, count = 5, speed = 600, size = 7, lifetime = 1.6, spread = 8 },
      { damage = 23, cooldown = 0.25, count = 5, speed = 620, size = 7, lifetime = 1.7, spread = 7, pierce = 1 },
    },
  },

  feedback_loop = {
    id          = "feedback_loop",
    name        = "Feedback Loop",
    description = "A focused sustained tone that accelerates as it ranks up.",
    archetype   = "projectile",
    role        = "Rapid focus",
    pattern     = "aimed",
    rarity      = "uncommon",
    icon        = { col = 4, row = 1 },
    projectile_color = { 0.28, 0.92, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 9, cooldown = 0.68, count = 1, speed = 470, size = 7, lifetime = 1.8, spread = 0 },
      { damage = 11, cooldown = 0.62, count = 1, speed = 480, size = 7, lifetime = 1.8, spread = 0 },
      { damage = 13, cooldown = 0.57, count = 2, speed = 490, size = 7, lifetime = 1.9, spread = 4 },
      { damage = 15, cooldown = 0.52, count = 2, speed = 500, size = 7, lifetime = 1.9, spread = 4 },
      { damage = 17, cooldown = 0.47, count = 2, speed = 510, size = 8, lifetime = 2.0, spread = 3 },
      { damage = 19, cooldown = 0.42, count = 2, speed = 520, size = 8, lifetime = 2.0, spread = 3, pierce = 1 },
      { damage = 21, cooldown = 0.38, count = 3, speed = 530, size = 8, lifetime = 2.1, spread = 5, pierce = 1 },
      { damage = 23, cooldown = 0.34, count = 3, speed = 540, size = 8, lifetime = 2.1, spread = 4, pierce = 1 },
      { damage = 26, cooldown = 0.30, count = 3, speed = 550, size = 9, lifetime = 2.2, spread = 4, pierce = 2 },
      { damage = 30, cooldown = 0.26, count = 4, speed = 570, size = 9, lifetime = 2.3, spread = 5, pierce = 2 },
    },
  },

  drum_circle = {
    id          = "drum_circle",
    name        = "Drum Circle",
    description = "Throws a complete ring of percussion around Joe.",
    archetype   = "spread",
    role        = "Radial control",
    pattern     = "radial",
    rarity      = "rare",
    icon        = { col = 1, row = 2 },
    projectile_color = { 0.28, 1.0, 0.70, 1 },
    max_level   = 10,
    levels = {
      { damage = 7, cooldown = 1.45, count = 6, speed = 330, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 8, cooldown = 1.36, count = 6, speed = 340, size = 6, lifetime = 1.5, spread = 0 },
      { damage = 9, cooldown = 1.28, count = 8, speed = 350, size = 6, lifetime = 1.6, spread = 0 },
      { damage = 10, cooldown = 1.20, count = 8, speed = 360, size = 7, lifetime = 1.6, spread = 0 },
      { damage = 12, cooldown = 1.12, count = 8, speed = 370, size = 7, lifetime = 1.7, spread = 0, pierce = 1 },
      { damage = 14, cooldown = 1.04, count = 10, speed = 380, size = 7, lifetime = 1.7, spread = 0, pierce = 1 },
      { damage = 16, cooldown = 0.96, count = 10, speed = 390, size = 8, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 18, cooldown = 0.88, count = 12, speed = 400, size = 8, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 21, cooldown = 0.80, count = 12, speed = 410, size = 8, lifetime = 1.9, spread = 0, pierce = 2 },
      { damage = 24, cooldown = 0.72, count = 14, speed = 420, size = 9, lifetime = 2.0, spread = 0, pierce = 2 },
    },
  },

  trumpet_burst = {
    id          = "trumpet_burst",
    name        = "Trumpet Burst",
    description = "A tight, forceful cone of brass notes with strong knockback.",
    archetype   = "spread",
    role        = "Close burst",
    pattern     = "aimed",
    rarity      = "common",
    icon        = { col = 2, row = 2 },
    projectile_color = { 1.0, 0.34, 0.28, 1 },
    max_level   = 10,
    levels = {
      { damage = 11, cooldown = 0.92, count = 3, speed = 470, size = 7, lifetime = 1.0, spread = 7, knockback = 16 },
      { damage = 13, cooldown = 0.86, count = 3, speed = 480, size = 7, lifetime = 1.0, spread = 7, knockback = 17 },
      { damage = 15, cooldown = 0.80, count = 4, speed = 490, size = 7, lifetime = 1.1, spread = 6, knockback = 18 },
      { damage = 17, cooldown = 0.74, count = 4, speed = 500, size = 8, lifetime = 1.1, spread = 6, knockback = 19 },
      { damage = 20, cooldown = 0.68, count = 5, speed = 510, size = 8, lifetime = 1.2, spread = 6, knockback = 20 },
      { damage = 23, cooldown = 0.62, count = 5, speed = 520, size = 8, lifetime = 1.2, spread = 5, knockback = 21 },
      { damage = 26, cooldown = 0.57, count = 6, speed = 530, size = 9, lifetime = 1.3, spread = 5, knockback = 22 },
      { damage = 29, cooldown = 0.52, count = 6, speed = 540, size = 9, lifetime = 1.3, spread = 5, knockback = 23 },
      { damage = 33, cooldown = 0.47, count = 7, speed = 550, size = 9, lifetime = 1.4, spread = 4, knockback = 24 },
      { damage = 38, cooldown = 0.42, count = 8, speed = 570, size = 10, lifetime = 1.5, spread = 4, knockback = 26 },
    },
  },

  vinyl_scratch = {
    id          = "vinyl_scratch",
    name        = "Vinyl Scratch",
    description = "Alternates cutting lanes to rake through packed crowds.",
    archetype   = "spread",
    role        = "Lane cutter",
    pattern     = "cross",
    rarity      = "uncommon",
    icon        = { col = 3, row = 2 },
    projectile_color = { 0.78, 0.30, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 13, cooldown = 0.88, count = 2, speed = 500, size = 7, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 15, cooldown = 0.82, count = 2, speed = 510, size = 7, lifetime = 1.8, spread = 0, pierce = 1 },
      { damage = 17, cooldown = 0.76, count = 3, speed = 520, size = 7, lifetime = 1.9, spread = 0, pierce = 1 },
      { damage = 20, cooldown = 0.70, count = 3, speed = 530, size = 8, lifetime = 1.9, spread = 0, pierce = 2 },
      { damage = 23, cooldown = 0.64, count = 4, speed = 540, size = 8, lifetime = 2.0, spread = 0, pierce = 2 },
      { damage = 26, cooldown = 0.58, count = 4, speed = 550, size = 8, lifetime = 2.0, spread = 0, pierce = 2 },
      { damage = 30, cooldown = 0.52, count = 5, speed = 560, size = 9, lifetime = 2.1, spread = 0, pierce = 2 },
      { damage = 34, cooldown = 0.47, count = 5, speed = 570, size = 9, lifetime = 2.1, spread = 0, pierce = 3 },
      { damage = 39, cooldown = 0.42, count = 6, speed = 580, size = 9, lifetime = 2.2, spread = 0, pierce = 3 },
      { damage = 45, cooldown = 0.37, count = 6, speed = 600, size = 10, lifetime = 2.3, spread = 0, pierce = 4 },
    },
  },

  synth_wave = {
    id          = "synth_wave",
    name        = "Synth Wave",
    description = "Projects a slow wall of oversized neon notes.",
    archetype   = "spread",
    role        = "Area wall",
    pattern     = "wall",
    rarity      = "rare",
    icon        = { col = 4, row = 2 },
    projectile_color = { 0.20, 0.96, 1.0, 1 },
    max_level   = 10,
    levels = {
      { damage = 16, cooldown = 1.30, count = 3, speed = 250, size = 14, lifetime = 2.4, spread = 18, pierce = 1 },
      { damage = 19, cooldown = 1.22, count = 3, speed = 260, size = 14, lifetime = 2.4, spread = 17, pierce = 1 },
      { damage = 22, cooldown = 1.14, count = 4, speed = 270, size = 15, lifetime = 2.5, spread = 16, pierce = 1 },
      { damage = 25, cooldown = 1.06, count = 4, speed = 280, size = 15, lifetime = 2.5, spread = 15, pierce = 2 },
      { damage = 29, cooldown = 0.98, count = 5, speed = 290, size = 16, lifetime = 2.6, spread = 14, pierce = 2 },
      { damage = 33, cooldown = 0.90, count = 5, speed = 300, size = 16, lifetime = 2.6, spread = 13, pierce = 2 },
      { damage = 38, cooldown = 0.82, count = 6, speed = 310, size = 17, lifetime = 2.7, spread = 12, pierce = 2 },
      { damage = 43, cooldown = 0.75, count = 6, speed = 320, size = 17, lifetime = 2.7, spread = 11, pierce = 3 },
      { damage = 49, cooldown = 0.68, count = 7, speed = 330, size = 18, lifetime = 2.8, spread = 10, pierce = 3 },
      { damage = 56, cooldown = 0.60, count = 8, speed = 340, size = 19, lifetime = 3.0, spread = 9, pierce = 4 },
    },
  },

  brass_barrage = {
    id          = "brass_barrage",
    name        = "Brass Barrage",
    description = "Studio evolution: a reliable piercing three-note burst.",
    archetype   = "spread",
    role        = "Studio evolution",
    pattern     = "aimed",
    rarity      = "evolved",
    icon        = { col = 1, row = 1 },
    projectile_color = { 1.0, 0.72, 0.18, 1 },
    max_level   = 1,
    evolved     = true,
    levels = {
      {
        damage = 42,
        cooldown = 0.36,
        count = 3,
        speed = 560,
        size = 9,
        lifetime = 2.0,
        spread = 12,
        pierce = 3,
      },
    },
  },

  improvised_solo = {
    id          = "improvised_solo",
    name        = "Improvised Solo",
    description = "Live evolution: an accelerating phrase with a higher groove ceiling.",
    archetype   = "projectile",
    role        = "Live evolution",
    pattern     = "cross",
    rarity      = "evolved",
    icon        = { col = 1, row = 1 },
    projectile_color = { 0.38, 1.0, 0.76, 1 },
    max_level   = 1,
    evolved     = true,
    levels = {
      {
        damage = 34,
        cooldown = 0.28,
        count = 2,
        speed = 620,
        size = 8,
        lifetime = 2.1,
        spread = 5,
        pierce = 2,
      },
    },
  },
}
